/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import historico.Transacoes;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.CadastrarBean;
import model.CadastrarDAO;
import model.UsuarioLogado;
/**
 *
 * @author farma
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    
public void popularTabela(String produto, double valor) {
    DefaultTableModel model = (DefaultTableModel) historicoTransacoes.getModel();

    Transacoes currentTransacao = new Transacoes();
    currentTransacao.setID(model.getRowCount() + 1);
    currentTransacao.setProduto(produto);
    currentTransacao.setValor(valor);

    Object[] obj = {
        currentTransacao.getID(),
        currentTransacao.getProduto(),
        currentTransacao.getValor()
    };

    model.addRow(obj);
}
    private void configurarTabela() {
    NumberFormat moedaBR = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
    //Centralizar os títulos
    DefaultTableCellRenderer headerCentralizado = (DefaultTableCellRenderer) historicoTransacoes.getTableHeader().getDefaultRenderer();
    headerCentralizado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    // Centralizar ID e Produto
    DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
    centralizado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    historicoTransacoes.getColumnModel().getColumn(0).setCellRenderer(centralizado); // ID
    historicoTransacoes.getColumnModel().getColumn(1).setCellRenderer(centralizado); // Produto
    historicoTransacoes.getColumnModel().getColumn(2).setCellRenderer(centralizado); // Tipo
    historicoTransacoes.getColumnModel().getColumn(3).setCellRenderer(centralizado); // Valor
    historicoTransacoes.getColumnModel().getColumn(4).setCellRenderer(centralizado); // Data

    // Formatação BR e centralização
    DefaultTableCellRenderer moedaCentralizada = new DefaultTableCellRenderer() {
        @Override
        protected void setValue(Object value) {
            if (value instanceof Number) {
                setText(moedaBR.format(value));
            } else {
                setText("");
            }
            setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        }
    };

    historicoTransacoes.getColumnModel().getColumn(3).setCellRenderer(moedaCentralizada);
}
    
    public void carregarTabelaHistorico() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) historicoTransacoes.getModel();
    model.setRowCount(0);

    CadastrarDAO dao = new CadastrarDAO();

    for (CadastrarBean c : dao.listar()) {
        LocalDate localDate = c.getData_movimentacao().toLocalDate();
        if(localDate.getMonthValue() == cbFiltroMes.getSelectedIndex() + 1){
        Object[] linha = {
            c.getId_movimentacao(),
            c.getDescricao_movimentacao(),
            c.getTipo_movimentacao(),
            c.getValor_movimentacao(),
            c.getData_movimentacao()
        };
        model.addRow(linha);
        }  
    }
}
    public void atualizarSaldoDiario(){ 
        double saldo = 0.0; 
        CadastrarDAO dao = new CadastrarDAO();

    for (CadastrarBean c : dao.listar()) {
          LocalDate localDate = c.getData_movimentacao().toLocalDate();
        if(localDate.getMonthValue() == cbFiltroMes.getSelectedIndex() + 1){
            if(c.getTipo_movimentacao().equalsIgnoreCase("Venda")){
                saldo += c.getValor_movimentacao();
            } else if(c.getTipo_movimentacao().equalsIgnoreCase("Despesa")){ 
                saldo -= c.getValor_movimentacao(); }} 
    } java.text.NumberFormat moedaBR = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("pt", "BR"));
    lblSaldoDiario.setText("Saldo diário: " + moedaBR.format(saldo));
    }


    
    public Inicio() {
        
        if(UsuarioLogado.getId() > 0){
        setTitle("Controle de Caixas - Bem-vindo, " + UsuarioLogado.getNome());
        initComponents();
        configurarTabela();
        carregarTabelaHistorico();
        atualizarSaldoDiario();
        
    }   else{
            new Login().setVisible(true);
            this.dispose();
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historicoTransacoes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnTestar = new javax.swing.JButton();
        lblSaldoDiario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbFiltroMes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        historicoTransacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID da transação", "Descrição", "Tipo", "Valor", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(historicoTransacoes);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Histórico de transações");

        btnTestar.setText("Cadastrar movimentação");
        btnTestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestarActionPerformed(evt);
            }
        });

        lblSaldoDiario.setForeground(new java.awt.Color(0, 0, 0));
        lblSaldoDiario.setText("Saldo diário");

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbFiltroMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        cbFiltroMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltroMesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)
                        .addGap(238, 238, 238)
                        .addComponent(lblSaldoDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFiltroMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTestar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSaldoDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltroMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTestar)
                    .addComponent(jButton1))
                .addGap(0, 138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestarActionPerformed
        // TODO add your handling code here:
        new Movimentacao().setVisible(true);
    }//GEN-LAST:event_btnTestarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbFiltroMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltroMesActionPerformed
        // TODO add your handling code here:
        atualizarSaldoDiario();
        carregarTabelaHistorico();
    }//GEN-LAST:event_cbFiltroMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTestar;
    private javax.swing.JComboBox<String> cbFiltroMes;
    private javax.swing.JTable historicoTransacoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSaldoDiario;
    // End of variables declaration//GEN-END:variables
}
